M48
; DRILL file {KiCad 9.0.0} date 2026-03-11T16:02:09-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-11T16:02:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X19.1Y-66.0
X19.7Y-24.0
X91.3Y-24.0
X91.3Y-66.0
M30
